### ISSUE TITLE
no video

### ISSUE THREAD

**Issue by dga4130-renato** [crobibero/jellyfin-plugin-tmdb-trailers#9] opened 2021-06-19 20:36 UTC
jellyfin 10.7.6
installed as docker linux ubuntu 21.04
shows the preview of the trailer buit not playing

**Comment by crobibero** [comment] 2021-06-19 20:37
Duplicate of https://github.com/crobibero/jellyfin-plugin-tmdb-trailers/issues/8

**Closed by crobibero** 2021-06-19 20:37 UTC
